AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  email-service

  Sample SAM Template for email-service

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15

Resources:
  EmailSenderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: email_sender/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        EmailSender:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

  EmailSenderQueueFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: email_sender/
      Handler: app.lambda_handler_sqs
      Runtime: python3.8
      Events:
        EmailSQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt EmailSqsQueue.Arn
            BatchSize: 10

  EmailSqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: EmailSqsQ
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt EmailSqsDLQ.Arn
        maxReceiveCount: 5

  EmailSqsDLQ:
    Type: AWS::SQS::Queue

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  EmailSenderApi:
    Description: "API Gateway endpoint URL for Prod stage for Email Sender function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  EmailSenderFunction:
    Description: "Send Email Lambda Function ARN"
    Value: !GetAtt EmailSenderFunction.Arn
  EmailSenderFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt EmailSenderFunctionRole.Arn
